# Generated by Django 4.1.13 on 2026-08-01 07:52

import django.core.files.storage
from django.db import migrations, models
import firmware.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('label', 'Label'), ('stock', 'Stock')], max_length=16)),
                ('version', models.CharField(max_length=64)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\LM_apps\\cups\\firmware_store'), upload_to=firmware.models.firmware_upload_to)),
                ('size', models.PositiveIntegerField(default=0, editable=False)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='firmware',
            index=models.Index(fields=['device_type', 'is_active'], name='firmware_fi_device__2a58a6_idx'),
        ),
        migrations.CreateModel(
            name='LabelFirmware',
            fields=[
            ],
            options={
                'verbose_name': 'Label firmware',
                'verbose_name_plural': 'Label firmware',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('firmware.firmware',),
        ),
        migrations.CreateModel(
            name='StockFirmware',
            fields=[
            ],
            options={
                'verbose_name': 'Stock firmware',
                'verbose_name_plural': 'Stock firmware',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('firmware.firmware',),
        ),
    ]
