# Generated by Django 4.1.13 on 2024-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0002_alter_label_comment_alter_label_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="comment",
            field=models.CharField(default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="data",
            field=models.CharField(default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="identifier",
            field=models.CharField(default="", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="order",
            field=models.CharField(default="", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="shop",
            field=models.CharField(default="", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="label",
            name="user",
            field=models.CharField(default="", max_length=50, null=True),
        ),
    ]
