# Generated by Django 4.1.13 on 2024-10-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0004_alter_label_comment_alter_label_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_company", models.CharField(max_length=100)),
                (
                    "user",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                (
                    "data",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "pre_advice",
                    models.CharField(blank=True, default="", max_length=8, null=True),
                ),
                (
                    "identifier",
                    models.CharField(blank=True, default="", max_length=12, null=True),
                ),
                (
                    "comment",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                (
                    "master_id",
                    models.CharField(blank=True, default="", max_length=15, null=True),
                ),
                (
                    "sku",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "deskription",
                    models.CharField(blank=True, default="", max_length=100, null=True),
                ),
                ("print_status", models.BooleanField(default=False)),
            ],
        ),
    ]
