# Generated by Django 4.1.13 on 2024-10-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0006_remove_labelstock_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labelstock",
            name="pre_advice",
            field=models.CharField(blank=True, default="", max_length=12, null=True),
        ),
    ]
