# Generated by Django 5.0.14 on 2026-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0007_alter_labelstock_pre_advice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('oh_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('kind', models.CharField(choices=[('intact', 'pelnowartosciowe'), ('damaged', 'uszkodzone')], default='intact', max_length=10)),
                ('lines_info', models.JSONField(blank=True, null=True)),
                ('print_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
