# Generated by Django 5.0.14 on 2026-10-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0008_returnlabel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnlabel',
            options={'verbose_name': 'Etykieta zwrotu', 'verbose_name_plural': 'Etykiety zwrotów'},
        ),
    ]
